### ISSUE TITLE
Support multicast API

### ISSUE THREAD

**Issue by noraesae** [noraesae/line#5]
- https://devdocs.line.me/ja/#multicast

It may take some time for me to actually work on this. If anyone's interested in implementing this, please feel free to leave a comment.

**Comment by noraesae** [comment]
Please look into [API.hs](https://github.com/noraesae/line/blob/master/src/Line/Messaging/API.hs) for the API references. Adding one may not be so difficult.

**Comment by isairz** [comment]
I will.

**Comment by noraesae** [comment]
Implemented.
