### ISSUE TITLE
Get UserID from Room and Group

### ISSUE THREAD

**Issue by eckyputrady** [noraesae/line#8]
In LINE [dev docs](https://devdocs.line.me/en/#webhook-event-object), Room and Group structure contains user ID. However, this library doesn't extract the user ID from the JSON. https://github.com/noraesae/line/blob/master/src/Line/Messaging/Webhook/Types.hs#L208

Anyway, this is a solid library. Thanks for working on this!

**Comment by noraesae** [comment]
User ID is attached only when the user has already agreed to Official Account user consent. Please refer to the official document for the detail.

- https://developers.line.me/messaging-api/obtaining-user-consent

Thanks.

**Comment by noraesae** [comment]
Yes, this SDK is out of date from some new APIs. Will work on in a while.

**Comment by eckyputrady** [comment]
Awesome! 🙂
